### ISSUE TITLE
PHP 7.4 fixtures

### ISSUE THREAD

**Issue by panvid** [laminas/laminas-console#10]
There are some little changes in PHP 7.4 with could break the normal usage of Laminas Console. Perhaps these things can be fixed:

- Failure return values of `fread()` is now `false` and not `''`, see https://github.com/laminas/laminas-console/blob/master/src/Adapter/AbstractAdapter.php#L531

**Comment by michalbundyra** [comment]
@dpauli Thanks for reporting. Can you provide also reference that it has been changed specifically on PHP 7.4? I couldn't see it anywhere. Thanks!

**Comment by panvid** [comment]
Sorry, here is the Changelog: https://www.php.net/manual/de/migration74.incompatible.php#migration74.incompatible.core.fread-fwrite

**Comment by michalbundyra** [comment]
@dpauli Thanks. Would you be able to provide PR with the fix?

**Comment by weierophinney** [comment]
> This package is **abandoned** and will receive no further development!
>
> We recommend using [laminas/laminas-cli](https://docs.laminas.dev/laminas-cli/).
